openapi: 3.0.0
info:
  title: Cisco Secure Access Alerting API
  version: 1.0.0
  description: Manage the alert rules in the organization and monitor the alerts generated by the alert rules.
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: admin/v2

security:
  - oauthFlow: []

tags:
 - name: Alert Rules
 - name: Alerts
 - name: Secure Access

paths:
  /alerting/rules:
    get:
      operationId: listAlertRules
      summary: List Alert Rules
      description: Get the alert rules for the organization.
      tags:
        - Alert Rules
        - Secure Access
      security:
        - oauthFlow:
            - admin.alertrules:read
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                type: array
                description: The list of the alert rules in the organization.
                items:
                  $ref: '#/components/schemas/AlertRule'
              example:
              - id: 48
                name: SFO-11 Group disconnected
                description: Alert when SFO-11 Group connectivity is lost
                severity: 2
                status: 1
                rule_type_id: 1
                organization_id: 3056800
                created_at: '2025-03-20T13:38:56Z'
                modified_at: '2025-07-03T18:27:12Z'
                notification_info:
                - type: email
                  recipients:
                  - admin@example.com
                conditions:
                  match_type: all
                  rows:
                  - field: region
                    value: US West-1
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'

    post:
      operationId: createAlertRule
      summary: Create Alert Rule
      description: Create an alert rule in the organization.
      tags:
        - Alert Rules
        - Secure Access
      security:
        - oauthFlow:
          - admin.alertrules:write
      requestBody:
        $ref: '#/components/requestBodies/CreateAlertRuleRequestBody'
      responses:
        '201':
          description: Created
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                type: object
                description: The properties of the created alert rule.
                properties:
                  message:
                    type: string
                    description: The message from the system about the creation of the alert rule.
                    example: Rule created successfully
              example:
                message: Rule created successfully
        '409':
          $ref: '#/components/responses/409Error'
        '422':
          $ref: '#/components/responses/422Error'
        '429':
          $ref: '#/components/responses/429Error'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'

    delete:
      operationId: deleteAlertRules
      summary: Delete Alert Rules
      description: Delete multiple alert rules. Provide a list of unique identifiers for the alert rules.
      tags:
        - Alert Rules
        - Secure Access
      security:
        - oauthFlow:
            - admin.alertrules:write
      requestBody:
        $ref: '#/components/requestBodies/DeleteAlertRuleRequestBody'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                type: object
                description: The properties of the deleted alert rules.
                properties:
                  success:
                    $ref: '#/components/schemas/success'
                  successfulIds:
                    $ref: '#/components/schemas/successfulIdsDelete'
                  errorIds:
                    $ref: '#/components/schemas/errorIdsInteger'
              example:
                success: true
                successfulIds:
                - 48
                - 49
                - 50
                errorIds: [ 100 ]
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '422':
          $ref: '#/components/responses/422Error'
        '429':
          $ref: '#/components/responses/429Error'
        '500':
          $ref: '#/components/responses/500Error'

  /alerting/rules/{ruleId}:
    get:
      operationId: getAlertRuleById
      summary: Get Alert Rule
      description: Get the details for an alert rule in the organization.
      tags:
        - Alert Rules
        - Secure Access
      security:
        - oauthFlow:
          - admin.alertrules:read
      parameters:
        - $ref: '#/components/parameters/ruleId'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertRule'
              example:
                id: 48
                name: SFO-11 Group disconnected
                description: Monitors SFO-11 Group connectivity
                severity: 2
                status: 1
                rule_type_id: 1
                organization_id: 3056800
                created_at: '2025-03-20T13:38:56Z'
                modified_at: '2025-07-03T18:27:12Z'
                notification_info:
                - type: email
                  recipients:
                  - admin@example.com
                conditions:
                  match_type: all
                  rows:
                  - field: region
                    value: US West-1
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '429':
          $ref: '#/components/responses/429Error'
    put:
      operationId: updateAlertRule
      summary: Update Alert Rule
      description: Update the properties of an alert rule.
      parameters:
        - $ref: '#/components/parameters/ruleId'
      tags:
        - Alert Rules
        - Secure Access
      security:
        - oauthFlow:
          - admin.alertrules:write
      requestBody:
        $ref: '#/components/requestBodies/UpdateAlertRuleRequestBody'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                type: object
                description: The properties of the updated alert rule.
                properties:
                  message:
                    type: string
                    description: The message from the system about the update of the alert rule.
                    example: Rule updated successfully
              example:
                message: Rule updated successfully
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '409':
          $ref: '#/components/responses/409Error'
        '422':
          $ref: '#/components/responses/422Error'
        #Error: Bad Request, Maximum 50 email recipients allowed per rule, found 100
        '429':
          $ref: '#/components/responses/429Error'
        '500':
          $ref: '#/components/responses/500Error'

  /alerting/rules/status:
    put:
      operationId: updateAlertRulesStatus
      summary: Update Status of Alert Rules
      description: Update the status of the alert rules.
      tags:
        - Alert Rules
        - Secure Access
      security:
        - oauthFlow:
          - admin.alertrules:write
      requestBody:
        $ref: '#/components/requestBodies/UpdateStatusAlertRuleRequestBody'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                type: object
                description: The properties of the updated status of the alert rules.
                properties:
                  success:
                    type: boolean
                    description: |-
                      Specifies whether the operation succeeded.
                      Returns false if any ID is invalid.
                    example: true
                  successfulIds:
                    $ref: '#/components/schemas/successfulIdsUpdateInteger'
                  errorIds:
                    $ref: '#/components/schemas/errorIdsInteger'
              example:
                success: true
                successfulIds: [ 1, 2, 3, 4]
                errorIds: [ 1, 2]
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '422':
          $ref: '#/components/responses/422Error'
        '429':
          $ref: '#/components/responses/429Error'
        '500':
          $ref: '#/components/responses/500Error'

  /alerting/alerts:
    get:
      operationId: listAlerts
      summary: List Alerts
      description: Get the properties of the alerts for the organization.
      tags:
        - Alerts
        - Secure Access
      security:
        - oauthFlow:
          - admin.alertrules:read
      parameters:
        - $ref: '#/components/parameters/filtersAlerts'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ListAlertsResponse'
                  - $ref: '#/components/schemas/totalCountAlertsResponse'
              examples:
                fullResponse:
                  $ref: '#/components/examples/fullResponse'
                fullResponseWithContext:
                  $ref: '#/components/examples/fullResponseWithContext'
                countOnly:
                  $ref: '#/components/examples/countOnly'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '429':
          $ref: '#/components/responses/429Error'

  /alerting/alerts/{alertId}:
    get:
      operationId: getAlertById
      summary: Get Alert
      description: Get the details for the specific alert sent by the system to the organization.
      tags:
        - Alerts
        - Secure Access
      security:
        - oauthFlow:
          - admin.alerts:read
      parameters:
        - $ref: '#/components/parameters/alertId'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
              examples:
                alertResponse:
                  $ref: '#/components/examples/alertOnlyResponse'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '429':
          $ref: '#/components/responses/429Error'

  /alerting/alerts/status:
    put:
      operationId: updateAlertsStatus
      summary: Update Status of Alerts
      description: Update the status of the alerts in the organization.
      tags:
        - Alerts
        - Secure Access
      security:
        - oauthFlow:
          - admin.alerts:write
      requestBody:
        $ref: '#/components/requestBodies/UpdateStatusAlertRequestBody'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                type: object
                description: The properties of the updated alert statuses.
                properties:
                  success:
                    type: boolean
                    description: |-
                      If all operations succeeded, the system returns `true`.
                      If any ID is invalid, the system returns `false`.
                    example: true
                  successfulIds:
                    $ref: '#/components/schemas/successfulIdsUpdateString'
                  errorIds:
                    $ref: '#/components/schemas/errorIdsString'
              example:
                success: true
                successfulIds:
                  - AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01
                errorIds:
                  - AL-2048-833125-1764567890123-3f9a1c4b2d7e8f21
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '422':
          $ref: '#/components/responses/422Error'
        '429':
          $ref: '#/components/responses/429Error'
        '500':
          $ref: '#/components/responses/500Error'

  /alerting/alerts/testNotifications/emails:
    post:
      operationId: sendAlertNotifications
      summary: Create Test Alert by Email
      description: |-
        Create a test notification and send the alert to the recipients configured in the alert rule.
      tags:
        - Alerts
        - Secure Access
      security:
        - oauthFlow:
          - admin.alerts:write
      requestBody:
        $ref: '#/components/requestBodies/TestNotificationsEmailRequestBody'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestEmailNotificationResponse'
              example:
                status: success
                message: All notifications sent successfully
                results:
                - type: email
                  success: true
                  recipients_count: 2
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '403':
          $ref: '#/components/responses/403Error'
        '404':
          $ref: '#/components/responses/404Error'
        '429':
          $ref: '#/components/responses/429Error'
        '500':
          $ref: '#/components/responses/500Error'

components:

  headers:

    Content-Type:
      schema:
        type: string
      description: The MIME content type of the response body.
      example: application/json

    Date:
      schema:
        type: string
        pattern: '^[0-90-90-90-9-0-90-9-0-90-9T0-90-9:0-90-9:0-90-9Z]+$'
      description: The date and time (ISO 8601-formatted timestamp) when the system returned the response.
      example: '2023-03-14T18:34:25Z'

  parameters:

    ruleId:
      name: ruleId
      in: path
      required: true
      description: The unique identifier of the alert rule.
      schema:
        type: integer
      example: 42

    alertId:
      name: alertId
      in: path
      required: true
      description: The unique identifier of the alert.
      schema:
        type: string
      example: AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01

    limit:
      name: limit
      in: query
      required: false
      description: The maximum number of items to return from the collection in the response.
      schema:
        type: integer
        default: 10
      example: 5

    offset:
      name: offset
      in: query
      required: false
      description: The place to start reading in the collection. The default offset is 0.
      schema:
        type: integer
        format: int64
        default: 0
      example: 0

    filtersAlerts:
      name: filters
      in: query
      schema:
        $ref: '#/components/schemas/filtersAlertObject'
      description: |-
        Filter the alerts by one or more properties.
        Specify the properties of the filters query parameter in the JSON format.

        Example:

        ```
        {
            "alert_name": "alert number 50",
            "created_after": '2025-01-01T00:00:00Z'
        }
        ```

  responses:

    400Error:
      description: Bad Request
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Bad Request
                example: Not found IAM key info for org 12355.
              status:
                type: integer
                description: The HTTP status code returned in the response.
                example: 400

    401Error:
      description: Unauthorized
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Unauthorized
                example: Authorization token is invalid.
              status:
                type: integer
                description: The HTTP status code returned in the response.
                example: 401

    403Error:
      description: Forbidden
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
                example: Forbidden
              status:
                type: integer
                description: The HTTP status code returned in the response.
                example: 403

    404Error:
      description: Not Found
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
                example: Not Found
              status:
                type: integer
                description: The HTTP status code returned in the response.
                example: 404

    409Error:
      description: Conflict
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
                example: A rule with this name already exists for this organization
              status:
                type: integer
                description: The HTTP status code returned in the response.
                example: 409

    422Error:
      description: Unprocessable Entity (Too many email recipients or webhooks in notification_info)
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Bad Request, Maximum 50 email recipients allowed per rule, found 100
              status:
                type: integer
                description: The HTTP status code returned in the response.
                example: 422
          example:
            error: Bad Request, Maximum 50 email recipients allowed per rule, found 100

    429Error:
      description: Too Many Requests
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
                example: Rate limit exceeded
              status:
                type: integer
                description: The HTTP status code returned in the response.
                example: 404

    500Error:
      description: Internal Server Error
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error message explaining the reason for failure.
                example: Internal Server Error
              status:
                type: integer
                description: The HTTP status code returned in the response.
                example: 500

  requestBodies:

    TestNotificationsEmailRequestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TestNotification'

    CreateAlertRuleRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            description: The properties of the alert rule used by the system to create an alert rule.
            required:
              - name
              - severity
              - status
              - rule_type_id
            properties:
                name:
                  $ref: '#/components/schemas/nameAlertRule'
                description:
                  $ref: '#/components/schemas/descriptionAlertRule'
                severity:
                  $ref: '#/components/schemas/severityAlert'
                status:
                  $ref: '#/components/schemas/statusAlertRule'
                rule_type_id:
                  $ref: '#/components/schemas/ruleTypeId'
                notification_info:
                  type: array
                  description: The list of notifications for the alert rule.
                  items:
                    $ref: '#/components/schemas/notificationInfoAlertRule'
                conditions:
                  $ref: '#/components/schemas/conditionsAlertRule'
          example:
            name: SFO-02 Hub down
            description: Alert when SFO-02 Hub is down
            severity: 1
            status: 1
            rule_type_id: 1
            notification_info:
              - type: email
                recipients:
                  - admin@example.com
            conditions:
              match_type: all
              rows:
                - field: tunnelGroupName
                  value: test2
                - field: region
                  value: US West-2

    UpdateAlertRuleRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            description: The properties of the alert rule used by the system to update an alert rule.
            properties:
                name:
                  $ref: '#/components/schemas/nameAlertRule'
                description:
                  $ref: '#/components/schemas/descriptionAlertRule'
                severity:
                  $ref: '#/components/schemas/severityAlert'
                status:
                  $ref: '#/components/schemas/statusAlertRule'
                rule_type_id:
                  $ref: '#/components/schemas/ruleTypeId'
                notification_info:
                  type: array
                  description: The list of notifications for the alert rule.
                  items:
                    $ref: '#/components/schemas/notificationInfoAlertRule'
                conditions:
                  $ref: '#/components/schemas/conditionsAlertRule'
          example:
            name: SFO-02 Hub down
            description: Alert when SFO-02 Hub is down
            severity: 1
            status: 1
            rule_type_id: 1
            notification_info:
              - type: email
                recipients:
                  - admin@example.com
            conditions:
              match_type: all
              rows:
                - field: tunnelGroupName
                  value: test2
                - field: region
                  value: US West-2

    DeleteAlertRuleRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            description: The properties of the alert rules used by the system to delete the alert rules.
            required:
              - ruleIds
            properties:
              ruleIds:
                type: array
                description: The list of rule IDs used by the system to delete the alert rules.
                maxItems: 100
                items:
                  type: integer
                  description: The numeric identifier used by the system to delete the alert rule.
                example:
                  - 48
                  - 49
                  - 50
            example:
              ruleIds:
              - 48
              - 49
              - 50

    UpdateStatusAlertRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            description: The properties of the alerts used by the system to update the alerts.
            required:
              - status
              - entity_ids
            properties:
              status:
                type: integer
                enum:
                  - 1
                  - 2
                description: |-
                  The numeric identifier of the alert status.
                  Use `1` to enable the alert or `2` to disable the alert.
                example: 1
              entity_ids:
                $ref: '#/components/schemas/entity_ids_alerts'

    UpdateStatusAlertRuleRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            description: The properties of the alert rules used by the system to update the alert rules.
            required:
              - status
              - entity_ids
            properties:
              status:
                type: integer
                enum:
                  - 1
                  - 2
                description: |-
                  The numeric identifier of the status for the alert rule.
                  Use `1` to enable the alert rule or `2` to disable the alert rule.
                example: 1
              entity_ids:
                $ref: '#/components/schemas/entity_ids_alert_rules'

  schemas:

    pattern_search:
      description: Provide a search pattern to query for by the alert name, alert rule name, or alert rule category name.
      type: string
      example: Network Tunnel

    created_after:
      description: |-
          Filter for the alerts in the collection that the system created after the timestamp.
          Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format.
          **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.
      type: string
      format: date-time
      example: "2024-01-01T00:00:00Z"

    only_active_alerts_count:
      description: Specify whether to query for the count of the active alerts only.
      type: boolean
      default: false
      example: true

    entity_ids_alert_rules:
      type: array
      description: The list of identifiers used by the system to update the alert rules.
      maxItems: 100
      minItems: 1
      items:
        type: integer
        description: The identifier of the alert rule. The system uses this identifier to update the alert rule.
        example: 1
      example:
        - 1
        - 2

    entity_ids_alerts:
      type: array
      description: The list of identifiers used by the system to update the alerts.
      maxItems: 100
      minItems: 1
      items:
        type: string
        description: The identifier of the alert. The system uses this identifier to update the alert.
        example: 1abc
      example:
        - 1adf
        - 2eed

    success:
      type: boolean
      description: |-
        Specifies whether the system completed all operations successfully.
        If any ID is invalid, the system is unable to complete the operation.
      example: true

    successfulIdsUpdateInteger:
      type: array
      description: The list of IDs for the alert rules that the system updated.
      items:
        type: integer
        description: The ID of the alert rule that the system updated.
        example: 1234
      example:
        - 1234

    successfulIdsUpdateString:
      type: array
      description: The list of IDs for the alert rules that the system updated.
      items:
        type: string
        description: The ID of the alert rule that the system updated.
        example: AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01
      example:
        - AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01

    successfulIdsDelete:
      type: array
      description: The list of IDs for the alert rules that the system deleted.
      items:
        type: integer
        description: The ID of the alert rule that the system deleted.
      example:
        - 1
        - 2
        - 3
        - 4

    errorIdsString:
      type: array
      description: |-
        The list of unique identifiers that either do no exist or the system failed to delete or update.
      items:
        type: string
        description: |-
          The unique identifier of the alert rule that does not exist or the system failed to delete or update.
        example: 100a
      example: [ 100a ]

    errorIdsInteger:
      type: array
      description: |-
        The list of unique identifiers that either do no exist or the system failed to delete or update.
      items:
        type: integer
        description: |-
          The unique identifier of the alert rule that does not exist or the system failed to delete or update.
        example: 100
      example: [ 100 ]

    createdAtAlertRule:
      type: string
      format: date-time
      description: The time and date (ISO 8601 timestamp) when the system created the alert rule.
      example: '2025-01-01T00:00:00Z'

    modifiedAtAlertRule:
      type: string
      format: date-time
      description: The time and date (ISO 8601 timestamp) when the system last modified the alert rule.
      example: '2025-01-01T00:00:00Z'

    createdAtAlert:
      type: string
      format: date-time
      description: The time and date (ISO 8601 timestamp) when the system created the alert.
      example: '2025-01-01T00:00:00Z'

    modifiedAtAlert:
      type: string
      format: date-time
      description: The time and date (ISO 8601 timestamp) when the system last modified the alert.
      example: '2025-01-01T00:00:00Z'

    include_context:
      description: Include the context field in each alert response. The context contains additional metadata about the alert.
      type: boolean
      default: false
      example: true

    time_range:
      type: object
      description: |-
          The start and end times that the system uses to filter the alerts in the collection.
      properties:
        start_time:
          type: string
          format: date-time
          description: |-
            The time and date (ISO 8601 timestamp) that begins the time range. The system uses
            the time range to filter for alerts in the collection.
            Use the 'YYYY-MM-DD HH:MM:SS' format.
          example: "2024-01-01 00:00:00"
        end_time:
          type: string
          format: date-time
          description: |-
            The time and date (ISO 8601 timestamp) that ends the time range. The system uses
            the time range to filter for alerts in the collection.
            Use the 'YYYY-MM-DD HH:MM:SS' format.
          example: "2024-12-31 23:59:59"
      example:
        start_time: "2024-01-01 00:00:00"
        end_time: "2024-12-31 23:59:59"

    event_time:
      type: string
      format: date-time
      description: The date and time (ISO 8601 timestamp) when the system recorded the event.
      example: '2024-10-22T10:30:00Z'

    idAlert:
      type: string
      description: The unique identifier of the alert.
      example: AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01

    idAlertRule:
      type: integer
      description: The unique identifier of the alert rule.
      example: 42

    idRule:
      type: integer
      description: The unique identifier of the associated rule.
      example: 42

    nameAlertRule:
      type: string
      maxLength: 255
      description: The unique name of the alert rule.
      example: Production VPN Tunnel Alert

    nameAlert:
      type: string
      description: The name of the alert.
      example: Production VPN Tunnel Alert

    organizationId:
      type: integer
      description: The unique identifier of the organization.
      example: 12345

    descriptionAlertRule:
      type: string
      maxLength: 100
      description: The description of the alert rule.
      example: Alert when production VPN tunnel disconnects

    descriptionAlert:
      type: string
      description: The description of the alert.
      example: Alert when SFO-11 Group connectivity is lost

    ruleTypeId:
      type: integer
      description: |-
        The identifier of the rule type.

        **Category: Connectivity**

        | Rule Type ID | Rule Type Name |
        | --- | --- |
        | 1 | Network tunnel group disconnected |
        | 2 | No traffic through network tunnel group |

        **Category: API Anomalies**

        | Rule Type ID | Rule Type Name |
        | --- | --- |
        | 3 | Too many requests to get an access token |
        | 4 | High percentage of API errors |
        | 5 | Large number of rate limit errors |
        | 6 | More than one client using an API credential |
        | 7 | Authentication failures |
        | 8 | Programmatic creation of more than one API credential |

        **Category: Data Usage**

        | Rule Type ID | Rule Type Name |
        | --- | --- |
        | 9 | Data usage approaching limit |

        **Category: Access Rule Changes**

        | Rule Type ID | Rule Type Name |
        | --- | --- |
        | 10 | Rule creation, deletion, changing or reordering |

        **Category: Behavior Analytics**

        | Rule Type ID | Rule Type Name |
        | --- | --- |
        | 11 | Impossible travel detected |
        | 12 | Bulk upload operations |
        | 13 | Bulk download operations |
        | 14 | Bulk delete operations |
        | 15 | DLP violation spike |
        | 16 | Upload from high-risk countries |
        | 17 | Upload to high-risk countries |
      example: 1

    severityAlert:
      type: integer
      enum:
        - 1
        - 2
        - 3
        - 4
      description: |-
        The severity of the alert. The supported severity levels are:
        - 1 (High)
        - 2 (Medium)
        - 3 (Low)
        - 4 (Info)
      example: 1

    statusAlertRule:
      type: integer
      enum:
        - 1
        - 2
      description: |-
        The status of the alert rule. The supported status types are:
        - 1 (Enabled)
        - 2 (Disabled)
      example: 1

    statusAlert:
      type: integer
      enum:
        - 1
        - 2
        - 3
        - 4
      description: |-
        The status of the alert. The supported status types are:
        - 1 (Active)
        - 2 (Dismissed)
        - 3 (Resolved)
        - 4 (Archived)
      example: 1

    totalAlerts:
      type: integer
      description: The total number of active alerts.
      example: 100

    notificationTypeEmail:
      type: string
      enum:
        - email
      description: The type of the notification.
      example: email

    notificationTypeAll:
      type: string
      enum:
        - email
        - webhook
      description: The type of the notification for the alert rule.
      example: webhook

    notificationInfoAlertRule:
      type: object
      description: The properties of the notification for the alert rule.
      properties:
        type:
          $ref: '#/components/schemas/notificationTypeAll'
        recipients:
          type: array
          description: The list of email recipients configured in the alert rule to receive the notification.
          minItems: 1
          maxItems: 50
          items:
            type: string
            format: email
            description: An email recipient for the notification.
          example:
            - admin@company.com
            - ops@company.com
        webhook_ids:
          type: array
          description: The list of unique identifiers for the Webhooks configured on the alert rule.
          items:
            type: string
            description: The unique identifier for the Webhook ID.
            example: 1abcde

    conditionsAlertRule:
      type: object
      description: The conditions that trigger the type of notification.
      properties:
        match_type:
          type: string
          enum:
            - all
            - any
            - ''
          description: |-
            Choose from one of the accepted conditions: `all` (AND), `any` (OR), or ''.
          example: all
        rows:
          type: array
          description: The list of conditions that the system uses to evaluate the alert rule.
          items:
            type: object
            description: The conditions that define the alert rule.
            required:
              - field
              - value
            properties:
              field:
                type: string
                description: The name of the condition.
              value:
                type: string
                description: The canonical name of the geographical region for the data center where the notification occurs.

    AlertRule:
      type: object
      description: The properties of the alert rule.
      properties:
        id:
          $ref: '#/components/schemas/idAlertRule'
        name:
          $ref: '#/components/schemas/nameAlertRule'
        description:
          $ref: '#/components/schemas/descriptionAlertRule'
        severity:
          $ref: '#/components/schemas/severityAlert'
        status:
          $ref: '#/components/schemas/statusAlertRule'
        rule_type_id:
          $ref: '#/components/schemas/ruleTypeId'
        notification_info:
          type: array
          description: List of notification configurations for this rule
          items:
            $ref: '#/components/schemas/notificationInfoAlertRule'
        organization_id:
          $ref: '#/components/schemas/organizationId'
        conditions:
          $ref: '#/components/schemas/conditionsAlertRule'
        created_at:
          $ref: '#/components/schemas/createdAtAlertRule'
        modified_at:
          $ref: '#/components/schemas/modifiedAtAlertRule'

    redirect_entity_url_ueba:
      type: string
      description: The URL for the entity in Secure Access.
      example: "https://dashboard.sse.cisco.com/org/8327040/secure/ueba/user/12345"

    redirect_entity_url_access_rules:
      type: string
      description: The URL for the entity in Secure Access.
      example: "https://dashboard.sse.cisco.com/org/8327040/secure/policy?ruleId=2312623"

    redirect_entity_url_label:
      type: string
      description: The label for the entity's redirect URL.
      example: View entity

    context:
      type: object
      description: |-
          The properties of the metadata for the context.
          The system includes this field in the response when the API request sets the `include_context=true` query parameter.
      example:
        redirect_entity_url: "https://dashboard.sse.cisco.com/org/8327040/secure/policy?ruleId=2313262"
        redirect_entity_url_label: Test Rule
        action: create

    access_rule_context:
      type: object
      description: The properties of the context for the changes to the access rules alerts.
      properties:
        redirect_entity_url:
          $ref: '#/components/schemas/redirect_entity_url_access_rules'
        redirect_entity_url_label:
          $ref: '#/components/schemas/redirect_entity_url_label'
        change_type:
          type: string
          description: The type of change made on the access rule.
          enum:
            - create
            - update
            - delete
          example: update
        changes_made:
          type: string
          description: The description of the changes made by the system on the access rule.
          example: Rule changed

    behavior_analytics_context:
      type: object
      description: The properties of the context for the Behavior Analytics (UEBA) alerts.
      properties:
        redirect_entity_url:
         $ref: '#/components/schemas/redirect_entity_url_ueba'
        redirect_entity_url_label:
          $ref: '#/components/schemas/redirect_entity_url_label'
        redirect_event_url:
          type: string
          description: The URL for the UEBA event in Secure Access.
          example: "https://dashboard.sse.cisco.com/org/8327040/secure/ueba/event/67890"

    Alert:
      type: object
      description: The properties of the alert.
      properties:
        alertId:
          $ref: '#/components/schemas/idAlert'
        organization_id:
          $ref: '#/components/schemas/organizationId'
        description:
          $ref: '#/components/schemas/descriptionAlert'
        status:
          $ref: '#/components/schemas/statusAlert'
        rule_id:
          $ref: '#/components/schemas/idRule'
        created_at:
          $ref: '#/components/schemas/createdAtAlert'
        modified_at:
          $ref: '#/components/schemas/modifiedAtAlert'
        name:
          $ref: '#/components/schemas/nameAlert'
        rule_type_id:
          $ref: '#/components/schemas/ruleTypeId'
        severity:
          $ref: '#/components/schemas/severityAlert'
        access_rule_context:
          $ref: '#/components/schemas/access_rule_context'
        behavior_analytics_context:
          $ref: '#/components/schemas/behavior_analytics_context'

    AlertWithAdditionalContext:
      anyOf:
        - $ref: '#/components/schemas/Alert'
        - $ref: '#/components/schemas/context'

    TestEmailNotificationResponse:
      type: object
      description: The properties of the test email notification.
      properties:
        status:
          type: string
          enum:
            - success
            - partial_success
            - failed
          description: The status of the notification.
          example: success
        message:
          type: string
          description: The message sent by the system.
          example: All notifications sent successfully
        results:
          type: array
          description: The list of detailed results for each type of notification.
          items:
            type: object
            description: The properties of the test email notification sent by the system.
            properties:
              type:
                $ref: '#/components/schemas/notificationTypeEmail'
              success:
                type: boolean
                description: Specifies whether the notification was sent by the system successfully.
                example: true
              error:
                type: string
                description: When the system fails to send the test message, the system reports an error message.
                example: Error in sending the test notification.
              recipients_count:
                type: integer
                description: The number of recipients of the test email notification.
                example: 2

    TestNotification:
      type: object
      description: The properties of the test notification.
      required:
        - name
        - type
        - severity
        - notification_info
      properties:
        name:
          type: string
          description: The name of the alert rule.
          example: Production VPN Tunnel Disconnected
        type:
          $ref: '#/components/schemas/ruleTypeId'
        severity:
          $ref: '#/components/schemas/severityAlert'
        conditions:
          $ref: '#/components/schemas/conditionsAlertRule'
        notification_info:
          type: array
          description: The list of notification details.
          minItems: 1
          items:
            $ref: '#/components/schemas/notificationInfoAlertRule'
        event_time:
          $ref: '#/components/schemas/event_time'
        redirect_link:
          type: string
          format: uri
          description: The URL of the alert page in Secure Access.
          example: https://dashboard.company.com/alerts/42

    totalCountAlertsResponse:
      type: object
      description: |-
        The total number of active alerts.
        Set `only_active_alerts_count=true` query parameter for the system to return the `total` field only.
      required: [ total ]
      properties:
        total:
          $ref: '#/components/schemas/totalAlerts'
      additionalProperties: false

    severityCounts:
      description: The number of alerts categorized by the severity.
      type: object
      additionalProperties:
        type: integer
        description: The severity and the number of alerts categorized by the severity.
      example:
        High: 30
        Medium: 40
        Low: 20
        Info: 10

    ListAlertsResponse:
      type: object
      description: The properties of the alerts with the alert metadata.
      required:
        - total
        - severityCounts
        - alerts
      properties:
        total:
          $ref: '#/components/schemas/totalAlerts'
        severityCounts:
          $ref: '#/components/schemas/severityCounts'
        alerts:
          type: array
          description: The list of the details for the alerts.
          items:
            $ref: '#/components/schemas/AlertWithAdditionalContext'
      example:
        total: 100
        severityCounts:
          High: 30
          Warning: 50
          Low: 20
        alerts:
          - alertId: AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01
            organization_id: 123
            description: Alert description
            status: 1
            rule_id: 1
            created_at: '2024-01-01T00:00:00Z'
            modified_at: '2024-01-01T00:00:00Z'
            name: Alert Name
            rule_type_id: 1
            severity: 1
            access_rule_context:
              redirect_entity_url: "https://dashboard.sse.cisco.com/org/8327040/secure/policy?ruleId=2313262"
              redirect_entity_url_label: Test Rule
              change_type: create
              changes_made: Rule created

    filtersAlertObject:
      type: object
      description: The properties of the filters query parameter. Filter for the attributes of the alerts.
      properties:
        status:
          $ref: '#/components/schemas/statusAlert'
        severity:
          $ref: '#/components/schemas/severityAlert'
        created_after:
          $ref: '#/components/schemas/created_after'
        modified_at:
          $ref: '#/components/schemas/modifiedAtAlert'
        alert_name:
          $ref: '#/components/schemas/nameAlert'
        pattern_search:
          $ref: '#/components/schemas/pattern_search'
        only_active_alerts_count:
          $ref: '#/components/schemas/only_active_alerts_count'        
        time_range:
          $ref: '#/components/schemas/time_range' 
        include_context:
          $ref: '#/components/schemas/include_context'

  securitySchemes:

    oauthFlow:
      type: oauth2
      description: The client credential flow.
      flows:
        clientCredentials:
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
          scopes:
            admin.alertrules:read: 'Read Alert Rules'
            admin.alertrules:write: 'Write Alert Rules'
            admin.alerts:read: 'Read Alerts'
            admin.alerts:write: 'Write Alerts'

  examples:

    alertOnlyResponse:
      summary: Full alerts response with list and counts.
      value:
        alertId: AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01
        organization_id: 8327040
        description: Access rule was modified
        status: 1
        rule_id: 48
        created_at: "2024-01-01T00:00:00Z"
        modified_at: "2024-01-01T00:00:00Z"
        name: Policy Change Alert
        rule_type_id: 10
        severity: 1
        access_rule_context:
          redirect_entity_url: "https://dashboard.sse.cisco.com/org/8327040/secure/policy?ruleId=2313262"
          redirect_entity_url_label: Test Rule
          change_type: create
          changes_made: Rule created

    fullResponse:
      summary: Full alerts response with list and counts.
      value:
        total: 100
        severityCounts:
          High: 30
          Medium: 50
          Low: 20
        alerts:
          - alertId: "AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01"
            organization_id: 8327040
            description: Access rule was modified
            status: 1
            rule_id: 48
            created_at: "2024-01-01T00:00:00Z"
            modified_at: "2024-01-01T00:00:00Z"
            name: Policy Change Alert
            rule_type_id: 10
            severity: 1
            access_rule_context:
              redirect_entity_url: "https://dashboard.sse.cisco.com/org/8327040/secure/policy?ruleId=2313262"
              redirect_entity_url_label: Test Rule
              change_type: create
              changes_made: Rule created

    fullResponseWithContext:
      summary: Full alerts response with include_context=true.
      value:
        total: 100
        severityCounts:
          High: 30
          Medium: 50
          Low: 20
        alerts:
          - alertId: "AL-2048-833125-1764567890123-3f9a1c4b2d7e8f01"
            organization_id: 8327040
            description: Access rule was modified
            status: 1
            rule_id: 48
            created_at: "2024-01-01T00:00:00Z"
            modified_at: "2024-01-01T00:00:00Z"
            name: Policy Change Alert
            rule_type_id: 10
            severity: 1
            access_rule_context:
              redirect_entity_url: "https://dashboard.sse.cisco.com/org/8327040/secure/policy?ruleId=2313262"
              redirect_entity_url_label: Test Rule
              change_type: create
              changes_made: Rule created
            context:
              redirect_entity_url: "https://dashboard.sse.cisco.com/org/8327040/secure/policy?ruleId=2313262"
              redirect_entity_url_label: Test Rule
              action: create
          - alertId: "AL-2048-833125-1764567890124-4g0b2d5c3e8f9g02"
            organization_id: 8327040
            description: Anomalous user behavior detected
            status: 1
            rule_id: 49
            created_at: "2024-01-02T10:30:00Z"
            modified_at: "2024-01-02T10:30:00Z"
            name: UEBA Alert
            rule_type_id: 12
            severity: 2
            behavior_analytics_context:
              redirect_entity_url: "https://dashboard.sse.cisco.com/org/8327040/secure/ueba/user/12345"
              redirect_entity_url_label: View User
            context:
              redirect_entity_url: "https://dashboard.sse.cisco.com/org/8327040/secure/ueba/user/12345"
              redirect_entity_url_label: "View User"
              action: update

    countOnly:
      summary: Count-only response
      value:
        total: 100
